"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = __importDefault(require("react"));
var lodash_1 = __importDefault(require("lodash"));
var Table = react_1.default.memo(function (props) {
    return (react_1.default.createElement("table", { className: props.className + " table table-hover" },
        react_1.default.createElement("thead", null,
            react_1.default.createElement("tr", null,
                react_1.default.createElement("th", { scope: "col", onClick: function () { return lodash_1.default.orderBy([], ["Type"], ['desc']); } }, "Type"),
                react_1.default.createElement("th", { scope: "col" }, "Column heading"),
                react_1.default.createElement("th", { scope: "col" }, "Column heading"),
                react_1.default.createElement("th", { scope: "col" }, "Column heading"))),
        react_1.default.createElement("tbody", null,
            react_1.default.createElement("tr", { className: "table-active" },
                react_1.default.createElement("th", { scope: "row" }, "Active"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content")),
            react_1.default.createElement("tr", null,
                react_1.default.createElement("th", { scope: "row" }, "Default"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content")),
            react_1.default.createElement("tr", { className: "table-primary" },
                react_1.default.createElement("th", { scope: "row" }, "Primary"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content")),
            react_1.default.createElement("tr", { className: "table-secondary" },
                react_1.default.createElement("th", { scope: "row" }, "Secondary"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content")),
            react_1.default.createElement("tr", { className: "table-success" },
                react_1.default.createElement("th", { scope: "row" }, "Success"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content")),
            react_1.default.createElement("tr", { className: "table-danger" },
                react_1.default.createElement("th", { scope: "row" }, "Danger"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content")),
            react_1.default.createElement("tr", { className: "table-warning" },
                react_1.default.createElement("th", { scope: "row" }, "Warning"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content")),
            react_1.default.createElement("tr", { className: "table-info" },
                react_1.default.createElement("th", { scope: "row" }, "Info"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content")),
            react_1.default.createElement("tr", { className: "table-light" },
                react_1.default.createElement("th", { scope: "row" }, "Light"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content")),
            react_1.default.createElement("tr", { className: "table-dark" },
                react_1.default.createElement("th", { scope: "row" }, "Dark"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content"),
                react_1.default.createElement("td", null, "Column content")))));
});
Table.defaultProps = {
    className: '',
};
exports.default = Table;
